# $NetBSD$

GIT_REPO=	https://code.rocketnine.space/tslocum/twins.git
GIT_REVISION=	cd8520468072c39914ce5c8f6900dd804848d7ad
PKGNAME=	twins-0
PKGREVISION=	1
CATEGORIES=	net

MAINTAINER=	dressupgeekout@gmail.com
HOMEPAGE=	https://twins.rocketnine.space/
COMMENT=	Gemini server written in Go
LICENSE=	mit

#CHECK_RELRO_SKIP=	bin/minio

#GO_BUILD_PATTERN=	--ldflags '-X github.com/minio/minio/cmd.Version=${GITHUB_TAG} -X github.com/minio/minio/cmd.ReleaseTag=${GITHUB_TAG}' .

GO_MODULE_FILES+=	code.rocketnine.space/tslocum/gmitohtml/@v/v1.0.4.mod
GO_MODULE_FILES+=	code.rocketnine.space/tslocum/gmitohtml/@v/v1.0.4.zip
GO_MODULE_FILES+=	github.com/go-restit/lzjson/@v/v0.0.0-20161206095556-efe3c53acc68.mod
GO_MODULE_FILES+=	github.com/gopherjs/gopherjs/@v/v0.0.0-20181017120253-0766667cb4d1.mod
GO_MODULE_FILES+=	github.com/gopherjs/gopherjs/@v/v0.0.0-20200217142428-fce0ec30dd00.mod
GO_MODULE_FILES+=	github.com/h2non/filetype/@v/v1.1.1.mod
GO_MODULE_FILES+=	github.com/h2non/filetype/@v/v1.1.1.zip
GO_MODULE_FILES+=	github.com/jtolds/gls/@v/v4.20.0+incompatible.mod
GO_MODULE_FILES+=	github.com/kballard/go-shellquote/@v/v0.0.0-20180428030007-95032a82bc51.mod
GO_MODULE_FILES+=	github.com/kballard/go-shellquote/@v/v0.0.0-20180428030007-95032a82bc51.zip
GO_MODULE_FILES+=	github.com/smartystreets/assertions/@v/v0.0.0-20180927180507-b2de0cb4f26d.mod
GO_MODULE_FILES+=	github.com/smartystreets/assertions/@v/v1.1.1.mod
GO_MODULE_FILES+=	github.com/smartystreets/goconvey/@v/v1.6.4.mod
GO_MODULE_FILES+=	github.com/yookoala/gofast/@v/v0.6.0.mod
GO_MODULE_FILES+=	github.com/yookoala/gofast/@v/v0.6.0.zip
GO_MODULE_FILES+=	github.com/yuin/goldmark/@v/v1.2.1.mod
GO_MODULE_FILES+=	golang.org/x/crypto/@v/v0.0.0-20190308221718-c2843e01d9a2.mod
GO_MODULE_FILES+=	golang.org/x/crypto/@v/v0.0.0-20191011191535-87dc89f01550.mod
GO_MODULE_FILES+=	golang.org/x/crypto/@v/v0.0.0-20200622213623-75b288015ac9.mod
GO_MODULE_FILES+=	golang.org/x/mod/@v/v0.3.0.mod
GO_MODULE_FILES+=	golang.org/x/net/@v/v0.0.0-20190311183353-d8887717615a.mod
GO_MODULE_FILES+=	golang.org/x/net/@v/v0.0.0-20190404232315-eb5bcb51f2a3.mod
GO_MODULE_FILES+=	golang.org/x/net/@v/v0.0.0-20190620200207-3b0461eec859.mod
GO_MODULE_FILES+=	golang.org/x/net/@v/v0.0.0-20200822124328-c89045814202.mod
GO_MODULE_FILES+=	golang.org/x/net/@v/v0.0.0-20201021035429-f5854403a974.mod
GO_MODULE_FILES+=	golang.org/x/sync/@v/v0.0.0-20190423024810-112230192c58.mod
GO_MODULE_FILES+=	golang.org/x/sync/@v/v0.0.0-20200625203802-6e8e738ad208.mod
GO_MODULE_FILES+=	golang.org/x/sync/@v/v0.0.0-20201020160332-67f06af15bc9.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.0.0-20190215142949-d0b11bdaac8a.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.0.0-20190412213103-97732733099d.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.0.0-20200323222414-85ca7c5b95cd.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.0.0-20200930185726-fdedc70b468f.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.0.0-20210119212857-b64e53b001e4.mod
GO_MODULE_FILES+=	golang.org/x/text/@v/v0.3.0.mod
GO_MODULE_FILES+=	golang.org/x/text/@v/v0.3.3.mod
GO_MODULE_FILES+=	golang.org/x/tools/@v/v0.0.0-20180917221912-90fa682c2a6e.mod
GO_MODULE_FILES+=	golang.org/x/tools/@v/v0.0.0-20190328211700-ab21143f2384.mod
GO_MODULE_FILES+=	golang.org/x/tools/@v/v0.0.0-20191119224855-298f0cb1881e.mod
GO_MODULE_FILES+=	golang.org/x/tools/@v/v0.0.0-20200908211811-12e1bf57a112.mod
GO_MODULE_FILES+=	golang.org/x/tools/@v/v0.1.0.mod
GO_MODULE_FILES+=	golang.org/x/tools/@v/v0.1.0.zip
GO_MODULE_FILES+=	golang.org/x/xerrors/@v/v0.0.0-20190717185122-a985d3407aa7.mod
GO_MODULE_FILES+=	golang.org/x/xerrors/@v/v0.0.0-20191011141410-1b5146add898.mod
GO_MODULE_FILES+=	golang.org/x/xerrors/@v/v0.0.0-20200804184101-5ec99f83aff1.mod
GO_MODULE_FILES+=	gopkg.in/check.v1/@v/v0.0.0-20161208181325-20d25e280405.mod
GO_MODULE_FILES+=	gopkg.in/ini.v1/@v/v1.38.2.mod
GO_MODULE_FILES+=	gopkg.in/yaml.v3/@v/v3.0.0-20210105161348-2e78108cf5f8.mod
GO_MODULE_FILES+=	gopkg.in/yaml.v3/@v/v3.0.0-20210107192922-496545a6307b.mod
GO_MODULE_FILES+=	gopkg.in/yaml.v3/@v/v3.0.0-20210107192922-496545a6307b.zip

.include "../../lang/go/go-module.mk"
.include "../../wip/mk/git-package.mk"
.include "../../mk/bsd.pkg.mk"
