# $NetBSD$

DISTNAME=	zrythm-1.0.0-alpha.6.0.1
PKGNAME=	zrythm-1.0.0
CATEGORIES=	games
MASTER_SITES=	https://www.zrythm.org/releases/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	dressupgeekout@gmail.com
HOMEPAGE=	https://www.zrythm.org
COMMENT=	XXX FIXME
LICENSE=	isc

FETCH_USE_IPV4_ONLY=	yes

USE_LANGUAGES=	c c++

#WRKSRC=		${WRKDIR}/openclonk-release-${PKGVERSION_NOREV}-src
#EXTRACT_USING=	gtar
#USE_CMAKE=	yes
#USE_LANGUAGES=	c c++
#USE_TOOLS+=	pkg-config
#GCC_REQD+=	4.9

#.include "../../audio/SDL2_mixer/buildlink3.mk"
#.include "../../audio/freealut/buildlink3.mk"
#.include "../../audio/libvorbis/buildlink3.mk"
#.include "../../audio/openal-soft/buildlink3.mk"
#.include "../../devel/SDL2/buildlink3.mk"
.include "../../devel/glib2/buildlink3.mk"
#.include "../../devel/readline/buildlink3.mk"
#.include "../../devel/zlib/buildlink3.mk"
#.include "../../graphics/freetype2/buildlink3.mk"
#.include "../../graphics/glew/buildlink3.mk"
#.include "../../graphics/png/buildlink3.mk"
#.include "../../multimedia/libogg/buildlink3.mk"
#.include "../../x11/gtk3/buildlink3.mk"
#.include "../../x11/gtksourceview3/buildlink3.mk"
#.include "../../mk/jpeg.buildlink3.mk"


.include "../../wip/libcyaml/buildlink3.mk"
.include "../../lang/guile22/buildlink3.mk"
.include "../../devel/meson/build.mk"
.include "../../mk/bsd.pkg.mk"
