# $NetBSD$

DISTNAME=	orx-1.11
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GITHUB:=orx/}

MAINTAINER=	dressupgeekout@gmail.com
HOMEPAGE=	https://orx-project.org/
COMMENT=	Portable game engine
LICENSE=	zlib

#NO_CONFIGURE=	yes
#USE_LANGUAGES=	c

.include "../../mk/bsd.pkg.mk"
