# $NetBSD$

#DISTNAME=	cpdup-git-${GIT_REVISION}
GIT_REPO=	https://github.com/DragonFlyBSD/cpdup
GIT_REVISION=	b384d1cfc872da4c3c680e32e77365c39e19dcf2
CATEGORIES=	misc

MAINTAINER=	cfkoch@edgebsd.org
HOMEPAGE=	https://github.com/DragonFlyBSD/cpdup
COMMENT=	Filesystem mirroring utility from DragonFly BSD
LICENSE=	modified-bsd	

USE_LANGUAGES=	c

MAKE_FILE=	GNUmakefile

.include "../../wip/mk/git-package.mk"
.include "../../mk/bsd.pkg.mk"
