# $NetBSD$

DISTNAME=	be-0.6.1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=asmedit/}
GITHUB_PROJECT= be
GITHUB_TAG=	7b165a4832d84aa83541e563f50727707e2f6d16

MAINTAINER=	namdak@tonpa.guru
HOMEPAGE=	https://github.com/asmedit/be
COMMENT=	Binary hex editor with retro disassemblers
LICENSE=	isc

USE_LANGUAGES+=	c
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
