# $NetBSD$

DISTNAME=	be-0.0.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=asmedit/}
GITHUB_TAG=	6c59e60623a6b60addd3aa2714951db11057c22a

MAINTAINER=	charlotte@NetBSD.org
HOMEPAGE=	https://5ht.co/be/
COMMENT=	Binary hex editor with retro disassemblers
LICENSE=	isc

USE_LANGUAGES+=	c
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
